apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: mesh-app
spec:
  selector:
    matchLabels:
      app: backend
  jwtRules:
  - issuer: testing@secure.istio.io
    jwks: |
      {
        "keys": [
          {
            "kty": "RSA",
            "n": "w7Zdf3A5E...<trimmed>...",
            "e": "AQAB"
          }
        ]
      }